/*GENERATED BY OBNC 0.17.2*/

#ifndef artSleep_h
#define artSleep_h

#include <obnc/OBNC.h>

#define artSleep__Seconds_ obnc__artSleep__Seconds_
void artSleep__Seconds_(OBNC_INTEGER duration_);

#define artSleep__Millis_ obnc__artSleep__Millis_
void artSleep__Millis_(OBNC_INTEGER duration_);

#define artSleep__Init obnc__artSleep__Init
void artSleep__Init(void);

#endif
