/*GENERATED BY OBNC 0.17.2*/

#include "artSleep.h"
#include <obnc/OBNC.h>
#include <unistd.h>

#define OBERON_SOURCE_FILENAME "artSleep.obn"

void artSleep__Seconds_(OBNC_INTEGER duration_)
{
  if (duration_ > 0) {
		sleep(duration_);  
	}
}

void artSleep__Millis_(OBNC_INTEGER duration_)
{
    if (duration_ > 0) {
		usleep(duration_); 
	}
}


void artSleep__Init(void)
{
}
